### PR TITLE
Merge from upstream

### PR DESCRIPTION
**Pull request by juleea**

### CODE REVIEW

**Comment by juleea** [comment]
@sinneduy @kurtzur we want to merge in the upstream changes in order to fix the bug that allowed clobbering an existing version of a gem on publish. Do these changes look compatible with the changes you made on our fork? Are there any changes you made that can go away with this new set of changes from upstream?

**Comment by kurtzur** [comment]
The only changes I made to our fork were ones that I added to the master repo, and then copied over. I see the commit listed here (the one that says my username). So should be good from my end.

**Comment by kurtzur** [comment]
@mallyvai

**Comment by sinneduy** [comment]
I have searched for a change to `lib/gemstash/cache.rb` and found none, so I believe this is safe

**Pull request merged**
